### ISSUE TITLE
ImportError: cannot import name 'contextfilter' from 'jinja2'

### ISSUE THREAD

**Issue by NChongyuan** [BIG-MAP/PRISMA#2]
Hello,
I am very interested in using your app to analyse my data. 
I am using a windows system. I have installed the miniconda3 on my computer and finished the windows_install_script part.
However, I met an error when launching it, as shown in the following:

``C:\Users\hy\PRISMA-main>call C:\Users\hy/Miniconda3/Scripts/activate.bat

(base) C:\Users\hy\PRISMA-main>call conda activate prisma

(prisma) C:\Users\hy\PRISMA-main>cd gui

(prisma) C:\Users\hy\PRISMA-main\gui>voila GUI.ipynb
Traceback (most recent call last):
  File "C:\Users\hy\miniconda3\envs\prisma\Scripts\voila-script.py", line 5, in <module>
    from voila.app import main
  File "C:\Users\hy\miniconda3\envs\prisma\lib\site-packages\voila\__init__.py", line 11, in <module>
    from .server_extension import _load_jupyter_server_extension # noqa
  File "C:\Users\hy\miniconda3\envs\prisma\lib\site-packages\voila\server_extension.py", line 19, in <module>
    from .handler import VoilaHandler
  File "C:\Users\hy\miniconda3\envs\prisma\lib\site-packages\voila\handler.py", line 29, in <module>
    from .exporter import VoilaExporter
  File "C:\Users\hy\miniconda3\envs\prisma\lib\site-packages\voila\exporter.py", line 15, in <module>
    from jinja2 import contextfilter
ImportError: cannot import name 'contextfilter' from 'jinja2' (C:\Users\hy\miniconda3\envs\prisma\lib\site-packages\jinja2\__init__.py)``

I have tried three installer versions of miniconda3 (python3.7, 3.8 and 3.9) but not working.

Thank you in advance.

**Comment by eibfl-dtu** [comment]
Hi, 

As I see the issue is related to some package PRISMA uses.  Unfortunatedly this is not a problem of PRISMA itself, but related to which packages and versions are installed in miniconda, so there is little I can from from PRISMAs side. To try solivng the problem, they [suggest](https://github.com/d2l-ai/d2l-book/issues/46) to either uninstall jinja and reinstall version 3.0, OR to upgrade another package called nbconvert to its latest version.  Hope this helps.

**Comment by NChongyuan** [comment]
Hi,

I tried both uninstalled the jinja2 then install the version 3.0.0 and update the nbconvert. But it still shows the same error.

 `(base) C:\Users\hy>conda list nbconvert
# packages in environment at C:\Users\hy\miniconda3:
#
# Name                    Version                   Build  Channel
nbconvert                 6.5.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

(base) C:\Users\hy>conda list jinja2
# packages in environment at C:\Users\hy\miniconda3:
#
# Name                    Version                   Build  Channel
jinja2                    3.0.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge`

**Comment by slgotting** [comment]
I ran into the same issue when creating a new Python3 Notebook with these versions:

Jinja2==3.1.2
nbconvert==7.0.0

Also I should mention that in a different virtual environment I was successful in creating a new one which had these versions:

Jinja2==3.0.1
nbconvert==6.4.4

However, upon updating the non-working virtual env to those, it still didn't work.

So for now I'll use the other venv

**Comment by clarenznet** [comment]
I had the same error and this is how i solved it: 
by running updates for jinja2==3.0.3 and nbconvert==6.4.4 which supports jupyterlab server

**Comment by shadzic** [comment]
Downgrading jinja2 and upgrading nbconvert did not work for me.
What worked is to use python version 3.10.6 in a pyenv virtualenv

**Comment by jdtibochab** [comment]
> I had the same error and this is how i solved it: by running updates for jinja2==3.0.3 and nbconvert==6.4.4 which supports jupyterlab server

Thanks! This worked for me

**Comment by lofilippini** [comment]
Downgrading jinja2 to 3.0.1 worked for me
